version: '3.8'

networks:
  waspl-network:
    external: true

services:
  mongodb:
    image: mongo:6
    container_name: waspl-mongodb
    restart: always
    ports:
      - "27017:27017"  # Exposition locale uniquement
    volumes:
      - ./mongodb:/data/db  # Persistance des données MongoDB
    env_file:
      - .env  # Chargement des variables sensibles
    networks:
      - waspl-network

  waspleditor:
    build: ./waspleditor
    container_name: waspl-editor
    restart: always
    ports:
      - "4000:4000"  # API Backend
      - "5173:5173"  # Frontend Vite.js (mode dev)
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./waspleditor:/app  # Montage du code source pour hot reload
      - /app/node_modules  # Empêche l'écrasement des dépendances
      - ./media:/app/media
      - ./shared:/app/shared
    command: ["sh", "-c", "npm install && npm run dev"]  # Mode hot-reload activé
    networks:
      - waspl-network

  waspltestrunner:
    build: ./waspltestrunner
    container_name: waspl-testrunner
    restart: always
    ports:
      - "3011:3011"  # API Backend
      - "5174:5174"  # Frontend Vite.js (mode dev)
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./waspltestrunner:/app  # Synchronisation du code source
      - /app/node_modules
      - ./media:/app/media
      - ./shared:/app/shared
    command: ["sh", "-c", "npm install && npm run dev & node server/index.js"]  # Mode hot-reload activé
    networks:
      - waspl-network
